services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
      target: build
    environment:
      DATABASE_URL: postgres://postgres:example@postgres_db_dev:5432/postgres
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
    networks:
      - postgres_db_network
