version: "3.9"
services:
  angular:
    build:
      dockerfile: Dockerfile
      context: https://github.com/opensandiego/sdvv-frontend.git#feat-docker-build
      args:
        buildtype: "build:api:local"
    ports:
      - "4200:80"
    depends_on:
      api:
        condition: service_healthy

  api:
    build:
      target: development
    volumes:
      - .:/usr/src/app
    command: >
      bash -c "npm run start:web:dev"

  worker:
    build:
      target: development
    volumes:
      - .:/usr/src/app
    command: >
      bash -c "npm run start:worker:dev"

  postgres_db_dev:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  initialize_data:
    volumes:
      - .:/usr/src/app

# # Uncomment out the service below if needed 
#   pgadmin:
#     extends:
#       file: common-services.yml
#       service: pgadmin
#     depends_on:
#       - postgres_db_dev
