version: "3.9"

services:
  worker:
    extends:
      file: common-services.yml
      service: worker
    build:
      target: production
    environment:
      CI: true
      DISABLE_QUEUE_PURGE: true
    command: >
      bash -c "node dist/apps/standalone-worker/main"
    depends_on:
      postgres_db_dev:
        condition: service_healthy
      redis:
        condition: service_healthy
    profiles:
      - process-commands

  worker-ci:
    extends:
      service: worker
    environment:
      DATABASE_URL:
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - process-commands-in-ci

  run_console:
    extends:
      file: common-services.yml
      service: initialize_data
    command: >
      bash 
      -c 
      "node -r ts-node/register apps/standalone-worker/src/console.ts ${CONSOLE_COMMAND:-update-elections}"
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - add-command

  postgres_db_dev:
    extends:
      file: common-services.yml
      service: postgres_base
    command: >
      -c ssl=on 
      -c ssl_cert_file=/etc/ssl/private/server.crt 
      -c ssl_key_file=/etc/ssl/private/server.key
    profiles:
      - process-commands

  redis:
    extends:
      file: common-services.yml
      service: redis
    profiles:
      - add-command
      - process-commands
      - process-commands-in-ci

  test_service:
    extends:
      file: common-services.yml
      service: tester
    depends_on:
      worker:
        condition: service_completed_successfully
      worker-ci:
        condition: service_completed_successfully
      run_console:
        condition: service_completed_successfully
    profiles:
      - add-command
      - process-commands
      - process-commands-in-ci
