# This docker-compose.yml is intended for run containers locally for development.
# To run olny this compose file and exclude the override run:
#  docker compose -f docker-compose.yml up
# To include the override run:
#  docker compose up
version: "3.9"
services:
  api:
    extends:
      file: common-services.yml
      service: api
    depends_on:
      run_migrations:
        condition: service_completed_successfully

  worker:
    extends:
      file: common-services.yml
      service: worker
    depends_on:
      run_migrations:
        condition: service_completed_successfully

  initialize_data:
    extends:
      file: common-services.yml
      service: initialize_data
    depends_on:
      redis:
        condition: service_healthy

  run_migrations:
    extends:
      file: common-services.yml
      service: run_migrations
    depends_on:
      postgres_db_dev:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres_db_dev:
    extends:
      file: common-services.yml
      service: postgres_base
    build:
      target: build

  redis:
    extends:
      file: common-services.yml
      service: redis
