# This docker-compose.yml is intended for run containers locally for development.
# To run olny this compose file and exclude the override run:
#  docker compose -f docker-compose.yml up
# To include the override run:
#  docker compose up
version: "3.9"
services:
  api:
    extends:
      file: common-services.yml
      service: server
    build:
      target: web
    depends_on:
      run_migrations:
        condition: service_completed_successfully
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:3000/health}"
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    ports:
      - 3000:3000

  worker:
    extends:
      file: common-services.yml
      service: server
    build:
      target: worker
    environment:
      PURGE_QUEUE: false
      CHECK_UPDATE_INTERVAL: true
      UPDATE_INTERVAL_HOURS: 10
    depends_on:
      run_migrations:
        condition: service_completed_successfully

  initialize_data:
    extends:
      file: common-services.yml
      service: server
    build: 
      target: development
    command: >
      bash -c "npm run db:initialize:data"
    depends_on:
      redis:
        condition: service_healthy

  run_migrations:
    extends:
      file: common-services.yml
      service: server
    build:
      target: development
    command: >
      bash -c "npm run db:migration:run"
    depends_on:
      postgres_db_dev:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres_db_dev:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - postgres_db_network

  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: >
     --requirepass secret 
    ports:
     - 6379:6379
    networks:
      - postgres_db_network

networks:
  postgres_db_network:
    driver: bridge
