# This docker-compose.yml is intended to run containers as a simulated 
# production environment.

# To run use:
#  docker compose build
# Then:
#  docker compose up

version: "3.9"
services:
  api:
    extends:
      file: common-services.yml
      service: api
    depends_on:
      run_migrations:
        condition: service_completed_successfully

# This runs every time docker compose up is run
# This takes a few minutes to complete
  initialize_data:
    extends:
      file: common-services.yml
      service: initialize_data
    build:
      target: production
    depends_on:
      run_migrations:
        condition: service_completed_successfully

  run_migrations:
    extends:
      file: common-services.yml
      service: run_migrations
    build:
      target: production
    depends_on:
      postgres_db_dev:
        condition: service_healthy

  postgres_db_dev:
    extends:
      file: common-services.yml
      service: postgres_ssl
