name: Build Test

on:
  workflow_call:

  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - run: docker compose -f docker-compose.yml build api
