name: Deploy to Heroku

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-to-heroku:
    name: Deploy to  ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:  ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v3

      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_ID }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
