name: Run TypeORM Command

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  run-typeorm-command:
    runs-on: ubuntu-latest
    environment:  ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Build Containers
        run : docker compose -f docker-compose.typeorm.yml build

      - name: Run command ${{ inputs.command }}
        run: |
          echo "::add-mask::DATABASE_URL"
          export DATABASE_URL=$(heroku config:get DATABASE_URL -a $APP_ID)
          docker compose -f docker-compose.typeorm.yml up --exit-code-from test_service
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_ID: ${{ secrets.HEROKU_APP_ID }}
          TYPEORM_COMMAND: ${{ inputs.command }}
