name: Run Console Commands

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  run-console-command:
    name: Run command ${{ inputs.command }}
    runs-on: ubuntu-latest
    environment:  ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Build Containers
        run : docker compose -f docker-compose.console.yml --profile add-command --profile process-commands-in-ci build

      - name: Add command ${{ inputs.command }} to queue
        run: docker compose -f docker-compose.console.yml --profile add-command up --exit-code-from test_service
        env:
          CONSOLE_COMMAND: ${{ inputs.command }}

      - name: Run commands in queue
        run: |
          echo "::add-mask::DATABASE_URL"
          export DATABASE_URL=$(heroku config:get DATABASE_URL -a $APP_ID)
          docker compose -f docker-compose.console.yml --profile process-commands-in-ci up --exit-code-from test_service
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_ID: ${{ secrets.HEROKU_APP_ID }}
