name: Scheduled Staging Updates

on:
  schedule:
  - cron: '10 3 * * *'
  - cron: '25 3 * * sat'
  - cron: '40 3 * * sun'

jobs:
  update-transactions-current-staging:
    if: github.event.schedule == '10 3 * * *'
    name: Current Transactions Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/updater
        with:
          command: update-transactions-current
          APP_ID: ${{ secrets.STAGING_HEROKU_APP_ID }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  update-transactions-past-staging:
    if: github.event.schedule == '25 3 * * sat'
    name: Past Transactions Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/updater
        with:
          command: update-transactions-past
          APP_ID: ${{ secrets.STAGING_HEROKU_APP_ID }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  update-candidates-current-staging:
    if: github.event.schedule == '40 3 * * sun'
    name: Current Candidates Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/updater
        with:
          command: update-candidates-current
          APP_ID: ${{ secrets.STAGING_HEROKU_APP_ID }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
