name: Scheduled Production Updates

on:
  schedule:
  - cron: '10 4 * * *'
  - cron: '25 4 * * sat'
  - cron: '40 4 * * sun'

jobs:
  update-transactions-current-production:
    if: github.event.schedule == '10 4 * * *'
    name: Current Transactions Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/updater
        with:
          command: update-transactions-current
          APP_ID: ${{ secrets.PRODUCTION_HEROKU_APP_ID }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  update-transactions-past-production:
    if: github.event.schedule == '25 4 * * sat'
    name: Past Transactions Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/updater
        with:
          command: update-transactions-past
          APP_ID: ${{ secrets.PRODUCTION_HEROKU_APP_ID }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  update-candidates-current-production:
    if: github.event.schedule == '40 4 * * sun'
    name: Current Candidates Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/updater
        with:
          command: update-candidates-current
          APP_ID: ${{ secrets.PRODUCTION_HEROKU_APP_ID }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
