name: Smoke Test

on:
  workflow_call:

  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Containers
        run : docker compose -f docker-compose.yml -f docker-compose.ci.yml --profile migrations --profile smoke_tester build 

      - name: Run compose with migrations
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml --profile migrations up --exit-code-from run_migrations

      - name: Run with only smoke test as an exiting container
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml --profile smoke-test up --exit-code-from smoke_tester
